# Generated by Django 4.0.4 on 2022-05-19 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
