# Generated by Django 4.0.4 on 2022-05-20 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_comments_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='questions.questions'),
        ),
    ]
